### PR TITLE
[feature] define shortcut macros for skip_error_and_log

### PR DESCRIPTION
**Pull request by woshilapin**
Defines these new shortcut macros:
- `skip_error_and_error`
- `skip_error_and_warn`
- `skip_error_and_info`
- `skip_error_and_debug`
- `skip_error_and_trace`

Also made a bunch of improvements to the documentation.

### CODE REVIEW

**Comment by woshilapin** [comment]
Waiting for Rust 1.54.0, we might be able to drop the `doc_comment` macro entirely (see first item of [pre-release notes](https://github.com/rust-lang/rust/blob/master/RELEASES.md#language)).

**Comment by woshilapin** [comment]
> Waiting for Rust 1.54.0, we might be able to drop the `doc_comment` macro entirely (see first item of [pre-release notes](https://github.com/rust-lang/rust/blob/master/RELEASES.md?rgh-link-date=2021-07-28T09%3A05%3A29Z#language)).

Rust 1.54.0 has been released and indeed, I've been able to simplify the code and remove the `doc_comment` macro. Note that this make this new version of the crate only compatible with Rust 1.54.0 though :thinking: I removed the `do_not_merge` label.

**Review by datanel — COMMENTED** [review]
Clippy fails because the rust version in [ruts-ci](https://hub.docker.com/layers/kisiodigital/rust-ci/latest/images/sha256-69b3d313fc77b8df216f890fe23389efe4b9256fa59a489a70b99a8ce9b1bbfd?context=repo) is not the last version

**Review by pbougue — APPROVED** [review]
The macro on macro is quite small, depending on rust 1.54 is OK, doc generation is readable enough and close for `skip_error_and_log`... To me, it's a "go" :)
One more review/opinion from the team would be nice.

**Comment by pbougue** [comment]
> Clippy fails because the rust version in [ruts-ci](https://hub.docker.com/layers/kisiodigital/rust-ci/latest/images/sha256-69b3d313fc77b8df216f890fe23389efe4b9256fa59a489a70b99a8ce9b1bbfd?context=repo) is not the last version

:heavy_check_mark: after update of ci-images

As discussed with @datanel we should state somewhere in doc that it requires rust `>=1.54` (not yet possible to state it in `Cargo.toml` AFAIK): maybe something like https://github.com/rust-random/rand#rust-version-requirements ?

**Comment by woshilapin** [comment]
I'm putting something in the `README` relative to the Minimum Supported Rust Version (MSRV): see 92f6dfff34d46b75b103d324aead0bdb1e3ed99d. Although, I'm wondering if this should be considered a breaking change, hence I should bump to version 3.0.0?

**Review by pbougue — APPROVED** [review]
To me it's not breaking as rust language itself is backward-compatible.
Although it's not so simple in CI corners, platform availability, etc.; so bumping a major version would also be OK to me.

**Comment by woshilapin** [comment]
> To me it's not breaking as rust language itself is backward-compatible.
> Although it's not so simple in CI corners, platform availability, etc.; so bumping a major version would also be OK to me.

It seems like some would have different opinion about what is breaking and what is not relative to MSRV (see [`bytemuck` crate](https://github.com/Lokathor/bytemuck#stability) for example). I would probably agree with the `bytemuck` strategy but if I'm the only one with this opinion, I'd be fine to keep this PR as it is.

**Comment by woshilapin** [comment]
I've moved to a major bump after an additional discussion with @datanel and @patochectp that seems to agree with me. Thanks everyone, the PR is ready to merge now.

**Pull request merged**
